### ISSUE TITLE
The entire server crashes when the client connection is closed prematurely 

### ISSUE THREAD

**Issue by timodempwolf** [oakserver/oak#586] opened 2023-02-04 13:49 UTC
I am running oak v11.1.0 on deno 1.30.2 in the alpine docker container.
What i see is that if the client is closing the connection prematurely for whatever reason the entire server crashes with the following error:
```
[uncaught application error]: Http - connection closed before message completed

    at Object.respondWith (deno:ext/http/01_http.js:259:21)
[uncaught application error]: Http - connection closed before message completed

request: { url: "http://localhost:9847/sieve", method: "GET", hasBody: false }
response: { status: 200, type: "text/plain", hasBody: true, writable: false }

    at Object.respondWith (deno:ext/http/01_http.js:259:21)
error: Uncaught (in promise) TypeError: cannot read headers: request closed
    return this.#request.headers;
                         ^
    at Object.get headerList (deno:ext/fetch/23_request.js:116:19)
    at Request.request.<computed> (deno:ext/fetch/23_request.js:620:43)
    at Request.get [headers] (deno:ext/fetch/23_request.js:267:48)
    at Request.get headers (deno:ext/fetch/23_request.js:482:18)
    at NativeRequest.get headers (https://deno.land/x/oak@v11.1.0/http_server_native_request.ts:68:26)
    at new Request (https://deno.land/x/oak@v11.1.0/request.ts:145:21)
    at new Context (https://deno.land/x/oak@v11.1.0/context.ts:173:20)
    at Application.#handleRequest (https://deno.land/x/oak@v11.1.0/application.ts:425:21)
    at Application.listen (https://deno.land/x/oak@v11.1.0/application.ts:610:28)
    at async file:///app/main.ts:44:1
```

I have been able to reproduce this multiple times. I have even tried to include a middleware to catch the error without success. This is quite a show-stopper as one bad user can teardown the entire server.

**Comment by rossholdway** [comment] 2023-02-09 16:26
This looks like a duplicate of https://github.com/oakserver/oak/issues/563. I agree, it's a pretty major bug. Unfortunately it seems as though the project as a whole is not very active at the moment...

**Comment by dvv** [comment] 2023-02-23 11:02
A workaround:
```js
addEventListener("error", event => {
  if (event.error.name === "TypeError" && event.error.message === "cannot read headers: request closed") {
    event.preventDefault()
    return
  }
  appLogger.critical(`Unhandled error: ${event.error.message}`, { stack: event.error.stack })
})
```

**Comment by kitsonk** [comment] 2023-03-03 05:30
Duplicate of #586

**Closed by kitsonk** 2023-03-03 05:30 UTC
Labels: duplicate
