### ISSUE TITLE
Is it possible to nest routers using method 'all' ?

### ISSUE THREAD

**Issue by phramos07** [oakserver/oak#100] opened 2020-05-21 03:52 UTC
Hi, I'm completely new to Deno. I'm used to working with `express.js` and I'm faced now with the following problem: how do I **nest routers** in oak? 

I tried using the method `all` like that, but it didn't work out. Does that make sense?

I have a controller `health.ts`:

```typescript
const checkHealth = async (ctx: Context) => { ... };

const router = new Router()
  .get("/", checkHealth);

export {
  router as healthRouter,
};
```

And I'm trying to **nest** this router into a parent router in my main entrypoint like that:

```typescript
import healthRouter as health from "../controllers/health.ts";

...

const parentRouter = new Router();
parentRouter.all("health", healthRouter.routes());
```

Does this make any sense or should I be doing my **own middleware** if I want to manage nested routes?

**Comment by ryhinchey** [comment] 2020-05-21 12:08
@phramos07 i think https://github.com/oakserver/oak/issues/6 is related to this issue.

**Comment by kitsonk** [comment] 2020-05-21 23:02
Duplicate of #6

**Closed by kitsonk** 2020-05-21 23:02 UTC
