### ISSUE TITLE
Static content space NotFound

### ISSUE THREAD

**Issue by ShayBox** [oakserver/oak#187] opened 2020-06-27 06:29 UTC
Using the provided [static content example](https://github.com/oakserver/oak#static-content)
Trying to access a url with spaces will fail with `NotFound`, Ex. `http://localhost:1337/example file.zip`
It's the same with a space, or %20 in the URL bar, the pathname for both is the full path with spaces encoded to %20, and a file of the name `example%20file.zip` does not exist on disk.

EDIT:
I created a reproducible template environment if you don't feel like setting one up.
https://github.com/ShayBox/Example-API

Create a file with a space in the name in `/static/directory` then open http://localhost:1337 in your browser and navigate to the file

**Comment by kitsonk** [comment] 2020-06-27 07:51
`.send()` needs to decode the URL path properly...

**Comment by kitsonk** [comment] 2020-07-04 06:27
I looked and `send()` properly decodes the path name, always has.  I also attempted to reproduce the issue, but I can't.  I've added a test specifically to test this, and it passes on all OSes supported by Deno:

https://github.com/oakserver/oak/blob/907d871556118d0f6388e80baeb3e79b220b67b4/send_test.ts#L211-L232

I've also created a static server locally and browsed some files with spaces in the path name, and it works fine.

**Comment by ShayBox** [comment] 2020-07-04 11:52
I'm able to recreate it with my project https://github.com/ShayBox/Example-API
create a zip file with a space in static/directory, start and go to the server, click the zip and it won't download.
![image](https://user-images.githubusercontent.com/9505196/86511902-5462e700-bdcb-11ea-9209-c0ce412ab7fe.png)

**Comment by kitsonk** [comment] 2020-07-04 20:49
I tried to re-create the issue, eliminating the rest of the code, and cannot reproduce locally:

<img width="996" alt="main_ts_—_oak_scratch_and_response_ts_—_oak" src="https://user-images.githubusercontent.com/1282577/86520790-a4a17e00-be8b-11ea-8452-b6bd5d0db961.png">

<img width="366" alt="localhost_1337_test_file_json" src="https://user-images.githubusercontent.com/1282577/86520796-b08d4000-be8b-11ea-8613-898855dbfde5.png">

**Comment by ShayBox** [comment] 2020-07-04 22:16
I found the problem, `ctx.request.url.pathname` isn't converting %20 into spaces which means my statSync is trying to stat `test%20file.zip`, so pathname isn't being coded like it should

**Comment by kitsonk** [comment] 2020-07-05 01:49
It shouldn't automatically decode the part. That is why `send()` does that itself using `decodeUriComponent()`.

Closing as this is working as designed.

**Closed by kitsonk** 2020-07-05 01:49 UTC
Labels: need info
