### ISSUE TITLE
maxAge cookie parameter should result in Max-Age parameter, not Expires parameter

### ISSUE THREAD

**Issue by gcocatre** [oakserver/oak#344] opened 2021-06-21 10:34 UTC
When passing a `maxAge` parameter when setting a cookie, I would expect the resulting `Set-Cookie` header to contain a `Max-Age` parameter. Instead it is forcibly converted to an `Expires` parameter, which it shouldn't be.

```
if (this.maxAge) {
    this.expires = new Date(Date.now() + (this.maxAge * 1000));
}
```

**Comment by kitsonk** [comment] 2021-06-28 02:04
I dug into this deeper.  The code for cookies was adapted from [PillarJs `cookies`](https://github.com/pillarjs/cookies) which also adapted it from a previous project.  While it might not be as relevant today, it basically boils down to that the `expires` directive always works while `max-age` doesn't in some legacy user agents, and so you would want to set both, which then sort of makes it redundant.  There is some more [information here](https://mrcoles.com/blog/cookies-max-age-vs-expires/).

Because of this, I am going to close this as working as designed.

**Closed by kitsonk** 2021-06-28 02:04 UTC
Labels: working as designed
