### ISSUE TITLE
Can't run the example from the documentation

### ISSUE THREAD

**Issue by florin-t** [oakserver/oak#170] opened 2020-06-15 11:47 UTC
While trying to run this example: 

```
import { Application } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

app.use((ctx) => {
  ctx.response.body = "Hello World!";
});

await app.listen({ port: 8000 });
```

with: 

`deno run --allow-net app.ts`

I get: 

Download https://deno.land/x/oak/mod.ts
**error**: Import 'https://deno.land/x/oak/mod.ts' failed: 404 Not Found

**Comment by kitsonk** [comment] 2020-06-15 11:49
Duplicate of #169

**Closed by kitsonk** 2020-06-15 11:49 UTC
