### ISSUE TITLE
Type '{}' is not asssignable to type 'RouteParams<R>'

### ISSUE THREAD

**Issue by Bonathan** [oakserver/oak#439] opened 2021-12-17 20:37 UTC
# Error message
As stated in the title I get following error message:
```
TS2322 [ERROR]: Type '{}' is not assignable to type 'RouteParams<R>'.
  let replace: RouteParams<R> = {};
      ~~~~~~~
    at https://deno.land/x/oak@v10.0.0/router.ts:227:7
```
<details>
<summary>There are four errors in total, stating almost the same issue: Type'{}' is not assignable to ... just at different locations in the code</summary>

```
error: TS2322 [ERROR]: Type '{}' is not assignable to type 'RouteParams<R>'.
  params: RouteParams<R> = {},
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v10.0.0/router.ts:223:3

TS2322 [ERROR]: Type '{}' is not assignable to type 'RouteParams<R>'.
  let replace: RouteParams<R> = {};
      ~~~~~~~
    at https://deno.land/x/oak@v10.0.0/router.ts:227:7

TS2322 [ERROR]: Type '{}' is not assignable to type 'RouteParams<R>'.
    existingParams: RouteParams<R> = {},
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v10.0.0/router.ts:301:5

TS2322 [ERROR]: Type '{}' is not assignable to type 'RouteParams<R>'.
    params: RouteParams<R> = {},
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v10.0.0/router.ts:321:5
```
</details>

# Steps to reproduce / my code
<details>
<summary>In the following section is the code I have written</summary>

```TypeScript
import { Application, Router } from "https://deno.land/x/oak/mod.ts";
import * as postgres from './authentication/postgresql.ts';

const app = new Application();
const router = new Router();

router
    .get('/signup', async (ctx) => {
        let response = await postgres.createUser(email, password);

        ctx.response.body = response[0];
    })
    .get('/signin', async (ctx) => {
        let response = await postgres.signInUser(email, password);

        ctx.response.body = response[0];
    });

app.use(router.routes())
app.use(router.allowedMethods())

await app.listen({ port: 8000 })
```

I am not fluent in either TypeScript nor Deno, so should my code contain errors that cause this problem please let me know .
</details>

### Deno Version
```deno 1.17.0 (release, x86_64-pc-windows-msvc)```
### V8 Version
```v8 9.7.106.15```
### TypeScript Version
```typescript 4.5.2```
### Oak Version
Newest Oak version, meaning I imported it as follows:
```import { Application, Router } from "https://deno.land/x/oak/mod.ts";```

**Comment by rabbitkiller-dev** [comment] 2021-12-18 01:35
#438

**Comment by kitsonk** [comment] 2021-12-18 08:44
Duplicate of #438

**Closed by kitsonk** 2021-12-18 08:44 UTC
Labels: duplicate
