### ISSUE TITLE
Q&A: Router prefix problem

### ISSUE THREAD

**Issue by StraightUpCode** [oakserver/oak#91] opened 2020-05-17 19:31 UTC
Hello! 
So I've been trying to use oak to tinker arround and found either a bug or I'm using it in an incorrect way.
I have the following router : 
```
const TodoRouter = new Router({
    prefix: '/api/todo'
}); 

TodoRouter.get('/' , async (ctx) => {
    console.log('api')
    ctx.response.body = "Hello world"
} )
```
**What I expected** : doing a Get request to localhost:port/api/todo would return "Hello World" 
**What happened** : Doing a Get Request to localhost:port/api/todo return nothing
![image](https://user-images.githubusercontent.com/28929736/82158041-68b24b00-9842-11ea-89d6-966dbfd2e0da.png)

So my Question is, when using a Router without a Prefix, the '/' route, work for either localhost:port and localhost:port/ so I would assume that with a prefix works the same, with that in mind is this the correct behaviour or a bug? 
Thanks in advance

**Comment by kitsonk** [comment] 2020-05-17 20:58
It feels like when not using the `strict` option, it should match.

**Comment by kitsonk** [comment] 2020-05-18 20:27
I am unable to reproduce with this:

```ts
import { Application, Router } from "https://deno.land/x/oak/mod.ts";

const router = new Router({
  prefix: "/api/todo",
});

router.get("/", (ctx) => {
  console.log("api");
  ctx.response.body = "Hello world!";
});

const app = new Application();

app.use(router.routes());
app.use(router.allowedMethods());

await app.listen({ port: 8000 });
```

**Comment by aldinp16** [comment] 2020-05-19 07:24
i try to debug the value return from `setPrefix()` method at `router.ts` and its look like method return missmatch regex. 

```/^\/api\/todo\/$/i ``` with `{ strict: true }` options.
```/^\/api\/todo\/(?:\/)?$/i``` without `strict` options (https://regex101.com/r/qZcPM7/1).
only match `/api/todo/` or `/api/todo//`, and not match `/api/todo`.
maybe it helps.

**Comment by FraserHamilton** [comment] 2020-05-19 19:16
I've encountered this issue and was able to reproduce with the example code you provided @kitsonk.

I wasn't able to access /api/todo but could access /api/todo/. It's worth noting that I don't think toggling strict is doing anything here because with strict disabled you can access /api/todo/ and api/todo// but still can't access /api/todo

**Comment by kitsonk** [comment] 2020-05-19 23:02
Yeah, sorry, I don't know what I was thinking.  Going back and looking at it, it doesn't work as expected.  Working on a fix now.

**Comment by Marguelgtz** [comment] 2020-05-22 01:58
just submitted a fix  😁👍🏼, wrong path was beign sent to `pathToRegexp()` when strict was false

**Comment by StraightUpCode** [comment] 2020-05-22 04:20
@kitsonk  @Marguelgtz  thanks for working on the fix! :)

**Comment by LauraBeatris** [comment] 2020-05-24 21:07
@Marguelgtz @kitsonk Thanks :smile:

**Comment by kitsonk** [comment] 2020-05-27 12:00
I believe this is fixed in master now.

**Closed by kitsonk** 2020-05-27 12:00 UTC
Labels: question
