### ISSUE TITLE
UnexpectedEof - early eof - Deno Deploy Log Error

### ISSUE THREAD

**Issue by mskian** [oakserver/oak#551] opened 2022-08-26 12:37 UTC
After Upgrading to the latest version Spotted the Below Error on Deno Deploy Live Logs

```sh
at async accept (https://deno.land/x/oak@v11.1.0/http_server_native.ts:93:38)
2022-08-26 12:27:05
[uncaught application error]: UnexpectedEof - early eof
```

No Log Warning issues on Previous Version

**Comment by cmorten** [comment] 2022-08-30 06:51
Potential duplicate of:

- #483 
- https://github.com/denoland/deploy_feedback/issues/179

**Comment by kitsonk** [comment] 2023-04-25 05:14
Duplicate of #483

**Closed by kitsonk** 2023-04-25 05:14 UTC
Labels: duplicate
