### ISSUE TITLE
Get Form Values from body.

### ISSUE THREAD

**Issue by devYusuf** [oakserver/oak#114] opened 2020-05-24 18:59 UTC
I tried to get form values from request.body but kept returning urlparamsimpl {} and I can't get form values from that.

**Comment by Waxoussou** [comment] 2020-05-24 20:34
Same issue here

**Comment by gjuoun** [comment] 2020-05-24 21:06
Duplicate of #109

**Comment by LauraBeatris** [comment] 2020-05-24 21:26
@devYusuf 

> The method resolves to a version of the request body. Currently oak supports request body types of JSON, text, and URL encoded form data. If the content type is missing, the request will be rejected with a 415 HTTP Error.

You may need to pass the content-type options in order to get the body data from the request.

**Comment by kitsonk** [comment] 2020-05-24 23:37
@devYusuf as stated by @LauraBeatris if you are missing a content-type it won't work.  If you still think it is an issue, please provide information a complete reproduction, including what the request looks like.

**Comment by devYusuf** [comment] 2020-05-25 03:09
@kitsonk and @Waxoussou , I did 
```
const body = ctx.request.body({
    contentTypes: {
        json: ['form']
    }
})
```
still, same thing

**Comment by kitsonk** [comment] 2020-05-25 03:42
@devYusuf you need to supply what sort of request you are making and `ctx.request.body()` returns an `Promise<Body>` and you are not awaiting the promise or otherwise handling the promise.

**Comment by lengfangbing** [comment] 2020-05-25 04:06
> @devYusuf you need to supply what sort of request you are making and `ctx.request.body()` returns an `Promise<Body>` and you are not awaiting the promise or otherwise handling the promise.

```javascript
    const body = {type: '', value: {}};
    if (ctx.request.hasBody) {
      const result = await ctx.request.body({
        contentTypes: {
          json: ['application/json'],
          form: ['multipart', 'urlencoded'],
          text: ['text']
        }
      });
      const {type, value} = result;
      if (type === 'form') {
        body.type = type;
        for (let [key, item] of value) {
          body.value[key] = item;
        }
      } else {
        Object.assign(body, result);
      }
    }
    ctx.body = body;
    await next();
```

I think it will work again.
I checked the code about send function.

![image](https://user-images.githubusercontent.com/46396510/82777183-f4019100-9e7f-11ea-9a05-20e224d2757a.png)
all the form type returns URLSearchParams instance. 
I upload my code here. You can check it.
[deno-demo.zip](https://github.com/oakserver/oak/files/4675149/deno-demo.zip)

**Comment by Waxoussou** [comment] 2020-05-25 09:47
> > @devYusuf you need to supply what sort of request you are making and `ctx.request.body()` returns an `Promise<Body>` and you are not awaiting the promise or otherwise handling the promise.
> 
> ```js
>     const body = {type: '', value: {}};
>     if (ctx.request.hasBody) {
>       const result = await ctx.request.body({
>         contentTypes: {
>           json: ['application/json'],
>           form: ['multipart', 'urlencoded'],
>           text: ['text']
>         }
>       });
>       const {type, value} = result;
>       if (type === 'form') {
>         body.type = type;
>         for (let [key, item] of value) {
>           body.value[key] = item;
>         }
>       } else {
>         Object.assign(body, result);
>       }
>     }
>     ctx.body = body;
>     await next();
> ```
> 
> I think it will work again.
> I checked the code about send function.
> 
> ![image](https://user-images.githubusercontent.com/46396510/82777183-f4019100-9e7f-11ea-9a05-20e224d2757a.png)
> all the form type returns URLSearchParams instance.
> I upload my code here. You can check it.
> [deno-demo.zip](https://github.com/oakserver/oak/files/4675149/deno-demo.zip)

i've tried to specified the request but still does not seem to work  :
```

const addProduct = async ({ request, response, params }) => {
    if (!request.hasBody) {
        response.status = 400;
        response.body = {
            success: false,
            msg: 'no data'
        }
    } else {
        const body = await request.body({
            contentTypes: {
                json: ['application/json'],
                form: [ 'multipart', 'urlencoded'],
                text: ['text']
            }
        });
        const { name, price } = body.value;
        console.log(body, name, price)

```

**Comment by lengfangbing** [comment] 2020-05-25 09:59
> > > @devYusuf you need to supply what sort of request you are making and `ctx.request.body()` returns an `Promise<Body>` and you are not awaiting the promise or otherwise handling the promise.
> > 
> > 
> > ```js
> >     const body = {type: '', value: {}};
> >     if (ctx.request.hasBody) {
> >       const result = await ctx.request.body({
> >         contentTypes: {
> >           json: ['application/json'],
> >           form: ['multipart', 'urlencoded'],
> >           text: ['text']
> >         }
> >       });
> >       const {type, value} = result;
> >       if (type === 'form') {
> >         body.type = type;
> >         for (let [key, item] of value) {
> >           body.value[key] = item;
> >         }
> >       } else {
> >         Object.assign(body, result);
> >       }
> >     }
> >     ctx.body = body;
> >     await next();
> > ```
> > 
> > 
> > I think it will work again.
> > I checked the code about send function.
> > ![image](https://user-images.githubusercontent.com/46396510/82777183-f4019100-9e7f-11ea-9a05-20e224d2757a.png)
> > all the form type returns URLSearchParams instance.
> > I upload my code here. You can check it.
> > [deno-demo.zip](https://github.com/oakserver/oak/files/4675149/deno-demo.zip)
> 
> i've tried to specified the request but still does not seem to work :
> 
> ```
> 
> const addProduct = async ({ request, response, params }) => {
>     if (!request.hasBody) {
>         response.status = 400;
>         response.body = {
>             success: false,
>             msg: 'no data'
>         }
>     } else {
>         const body = await request.body({
>             contentTypes: {
>                 json: ['application/json'],
>                 form: [ 'multipart', 'urlencoded'],
>                 text: ['text']
>             }
>         });
>         const { name, price } = body.value;
>         console.log(body, name, price)
> ```

yes, just like what I mentioned. 
![image](https://user-images.githubusercontent.com/46396510/82802121-f4665000-9eb0-11ea-885c-d1aa4d3a9ee6.png)
If the type is form, It will work on x-www-form-urlencoded, but for formdara, it doesnt work.
I find one function in deno's std/mime/multipart.ts that could work with using MultipartReader class. But I got another error. I created a new issue for deno;
[https://github.com/denoland/deno/issues/5830](url)

**Comment by Waxoussou** [comment] 2020-05-25 10:05
> If the type is form, It will work on x-www-form-urlencoded, but for formdara, it doesnt work.
I find one function in deno's std/mime/multipart.ts that could work with using MultipartReader class. But I got another error. I created a new issue for deno;
https://github.com/denoland/deno/issues/5830


x-www-form-urlencoded is not working for me ... that my point ... whereas formdata is working for me ... :/

**Comment by lengfangbing** [comment] 2020-05-25 10:10
> > If the type is form, It will work on x-www-form-urlencoded, but for formdara, it doesnt work.
> > I find one function in deno's std/mime/multipart.ts that could work with using MultipartReader class. But I got another error. I created a new issue for deno;
> > [denoland/deno#5830](https://github.com/denoland/deno/issues/5830)
> 
> x-www-form-urlencoded is not working for me ... that my point ... whereas formdata is working for me ... :/

aha? urlencoded could parse to UrlSearchParams, but formdata has boundary and other symbol, it should not work on formdata. X_X.

**Comment by Waxoussou** [comment] 2020-05-25 10:22
> > > If the type is form, It will work on x-www-form-urlencoded, but for formdara, it doesnt work.
> > > I find one function in deno's std/mime/multipart.ts that could work with using MultipartReader class. But I got another error. I created a new issue for deno;
> > > [denoland/deno#5830](https://github.com/denoland/deno/issues/5830)
> > 
> > 
> > x-www-form-urlencoded is not working for me ... that my point ... whereas formdata is working for me ... :/
> 
> aha? urlencoded could parse to UrlSearchParams, but formdata has boundary and other symbol, it should not work on formdata. X_X.

i know should not ... but here what i get with urlencoded :
<img width="957" alt="Capture d’écran 2020-05-25 à 12 20 33" src="https://user-images.githubusercontent.com/45203020/82804288-4c399280-9e82-11ea-8147-c010eaf6a374.png">


and with form-data : 
<img width="703" alt="Capture d’écran 2020-05-25 à 12 20 52" src="https://user-images.githubusercontent.com/45203020/82804326-5fe4f900-9e82-11ea-890e-21d733213e60.png">

(using Postman)

**Comment by lengfangbing** [comment] 2020-05-25 10:40
> > > > If the type is form, It will work on x-www-form-urlencoded, but for formdara, it doesnt work.
> > > > I find one function in deno's std/mime/multipart.ts that could work with using MultipartReader class. But I got another error. I created a new issue for deno;
> > > > [denoland/deno#5830](https://github.com/denoland/deno/issues/5830)
> > > 
> > > 
> > > x-www-form-urlencoded is not working for me ... that my point ... whereas formdata is working for me ... :/
> > 
> > 
> > aha? urlencoded could parse to UrlSearchParams, but formdata has boundary and other symbol, it should not work on formdata. X_X.
> 
> i know should not ... but here what i get with urlencoded :
> <img alt="Capture d’écran 2020-05-25 à 12 20 33" width="957" src="https://user-images.githubusercontent.com/45203020/82804288-4c399280-9e82-11ea-8147-c010eaf6a374.png">
> 
> and with form-data :
> <img alt="Capture d’écran 2020-05-25 à 12 20 52" width="703" src="https://user-images.githubusercontent.com/45203020/82804326-5fe4f900-9e82-11ea-890e-21d733213e60.png">
> 
> (using Postman)

yeah , we are same. for urlencoded, you can use for of to get value. But for formData, it parsed in a wrong way in fact.

**Comment by LauraBeatris** [comment] 2020-05-25 11:23
@lengfangbing @Waxoussou 

Have you guys tried to use ```MultipartReader```?

For instance:
```
      const contentType = req.headers.get("content-type");
      const boundary = contentType.match(/boundary=([^\s]+)/)[1];
      const reader = new MultipartReader(req.body, boundary);
      const form = await reader.readForm(1024 * 1024); // 1MB
      console.log(form);
```

[Reference](https://gist.github.com/artisonian/8297e5fe95f448ca98045f336bccf976)

**Comment by lengfangbing** [comment] 2020-05-25 11:27
> @lengfangbing @Waxoussou
> 
> Have you guys tried to use `MultipartReader`?
> 
> For instance:
> 
> ```
>       const contentType = req.headers.get("content-type");
>       const boundary = contentType.match(/boundary=([^\s]+)/)[1];
>       const reader = new MultipartReader(req.body, boundary);
>       const form = await reader.readForm(1024 * 1024); // 1MB
>       console.log(form);
> ```
> 
> [Reference](https://gist.github.com/artisonian/8297e5fe95f448ca98045f336bccf976)

I tried, but got error. You can find here.
[https://github.com/denoland/deno/issues/5830](url)

**Comment by devYusuf** [comment] 2020-05-25 12:14
still getting the same thing!

**Comment by lengfangbing** [comment] 2020-05-25 12:18
> still getting the same thing!

Yes, I am focusing this issue, hhh XD~. 
I use MultipartReader to rewrite function that get request body. But got another issue, I create new issue in https://github.com/denoland/deno/issues/5830. We have a long way to go!

**Comment by gjuoun** [comment] 2020-05-25 21:00
@kitsonk @devYusuf @lengfangbing @Waxoussou 
Hey folks, I wrote a tool for parsing form-data
https://github.com/deligenius/multiparser

Please share and maybe give me some feedback.

**Comment by kitsonk** [comment] 2020-05-25 23:38
Lots of good conversations here, but oak doesn't currently support multi-part form data, but it should.  I am going to close this as a duplicate of #109 as that was the first to bring it up, and I think I have enough information now to try to solve the problem.

Duplicate of #109

**Closed by kitsonk** 2020-05-25 23:38 UTC
Labels: need info

**Comment by lengfangbing** [comment] 2020-05-26 02:25
> @kitsonk @devYusuf @lengfangbing @Waxoussou
> Hey folks, I wrote a tool for parsing form-data
> https://github.com/deligenius/multiparser
> 
> Please share and maybe give me some feedback.

sounds great hhh

**Comment by lengfangbing** [comment] 2020-05-26 02:40
> @kitsonk @devYusuf @lengfangbing @Waxoussou
> Hey folks, I wrote a tool for parsing form-data
> https://github.com/deligenius/multiparser
> 
> Please share and maybe give me some feedback.

I use this parser. But it may get some error. 
I used postman to send multipart/form-data request, but it was sending forever and never stop. 
I think it had no condition to stop read? or other reason?
![image](https://user-images.githubusercontent.com/46396510/82855115-ff66c200-9f3c-11ea-91ef-bd4fd8103456.png)
The output terminal had no error message. If I cancel the request, It showed error.
![image](https://user-images.githubusercontent.com/46396510/82855176-2cb37000-9f3d-11ea-8334-c337a5bed768.png)
I think thats the same question here https://github.com/denoland/deno/issues/5830

**Comment by gjuoun** [comment] 2020-05-26 02:48
@lengfangbing you can make an issue in that repo and then we can start the conversation there.

**Comment by lengfangbing** [comment] 2020-05-26 02:54
> @lengfangbing you can make an issue in that repo and then we can start the conversation there.

Ok, I made one issue there ~

**Comment by peterdee** [comment] 2020-05-29 23:29
Ok, so I've created a custom solution for **application/x-www-form-urlencoded** data parsing.

I've tested it with Postman:
<img width="607" alt="Screenshot 2020-05-30 at 02 05 56" src="https://user-images.githubusercontent.com/26158325/83312266-578e1480-a21a-11ea-8123-934b5f10ede1.png">
<img width="539" alt="Screenshot 2020-05-30 at 02 06 38" src="https://user-images.githubusercontent.com/26158325/83312271-5a890500-a21a-11ea-87f1-721c0e6cff6a.png">

This is the body parser:
https://github.com/peterdee/deno-oak-books/blob/stage/utilities/body-parser.ts

This is how it can be used:

```typescript
import bodyParser from '../../utilities/body-parser.ts';

export default async function (ctx: RouterContext): Promise<void> {
  try {
    const {
      email = '',
      password = '',
    }: LoginData = await bodyParser(ctx, ['email', 'password']);
    console.log('email:', email, 'password:', password);
    return;
  } catch (error) {
    /* ... */
  }
}
```

Console output:
```text
-- DENO + OAK is running on 9922 [DEV] 
email: sample@sample.com password: qwerty
POST /api/login 200 - 1ms
```

You can find the full controller code here:
https://github.com/peterdee/deno-oak-books/blob/stage/apis/login/login.controller.ts

This parser works, but there are some obvious issues:
1. Body is converted to a string that looks like this:
```text
key1=value1&key2=value2&key3=value3
``` 
It becomes nearly impossible to properly parse it if you get more form fields from the client than you expect.
2. This solution will not work for any complicated data structures.
3. The values cannot contain the key string in them, otherwise the parsing will go wrong.

The 3rd issue could be somewhat negated with Base64 data encoding.

If anyone knows a better solution for the **application/x-www-form-urlencoded** data parsing in oak please let me know. Thank you.
