### ISSUE TITLE
error sending request for url

### ISSUE THREAD

**Issue by mrxu0** [oakserver/oak#229] opened 2020-08-17 08:19 UTC
error sending request for url (https://raw.githubusercontent.com/pillarjs/path-to-regexp/v6.1.0/src/index.ts): error trying to connect: dns error: 请求的名称有效，但是找不到请求的类型的数据。 (os error 11004)

**Comment by kitsonk** [comment] 2020-08-19 02:34
Duplicate of #133

**Closed by kitsonk** 2020-08-19 02:34 UTC
Labels: duplicate
