### ISSUE TITLE
the newest version body is undefined with `const body = await context.request.body({ type: "json" }).value;`

### ISSUE THREAD

**Issue by dotku** [oakserver/oak#670] opened 2024-08-30 00:58 UTC
```
import { Application, Router } from "https://deno.land/x/oak/mod.ts";

const router = new Router();

router.get("/", (context) => {
  context.response.body = {
    version: "0.0.2"
  }
});

router.post("/", async (context) => {
  const body = await context.request.body({ type: "json" }).value;
  console.log('body', body);
  context.response.body = { status: "success", received: body };
});


const app = new Application();

app.use(router.routes());

try {
  console.log("Starting server on port 80...");
  await app.listen();  // Listen on port 80
} catch (error) {
  console.error("Failed to start server:", error.message);
  console.error("Stack trace:", error.stack);
}
```

can anyone help?
I aslo tested different version, won't address the issue...

fork the code here

https://dash.deno.com/playground/oak-body-debug

**Comment by kitsonk** [comment] 2024-08-30 01:18
Duplicate of #631 and #634.

**Closed by kitsonk** 2024-08-30 01:18 UTC
Labels: duplicate
