### ISSUE TITLE
Trying to accept a websocket connection inside a oak middleware

### ISSUE THREAD

**Issue by rishiraj824** [oakserver/oak#142] opened 2020-06-01 06:40 UTC
I am trying to accept a WebSocket connection request from the client. In order to do that I need access to `request.r`, `request.w` buffers. This is how I am using it or rather expecting it to work.
```
// server.ts
import socketRoute from './sock.ts';
app.use(socketRoute);`

// sock.ts
export default async (ctx: any) => {
  const { request } = ctx;
  console.log(request.r); // undefined
  console.log(request.w); // undefined
  ...
  acceptWebSocket({
        conn: request.conn,
        bufReader: request.r,
        bufWriter: request.w,
        headers: request.headers,
     })
}
```
This works while using `serve(PORT)` using the example in this [link](https://deno.land/std/ws/README.md). Another question was that the [request interface](https://github.com/oakserver/oak/blob/master/request.ts) inside oak does not have these buffers available so it would not support `ws` or there needs to be a different approach here.  

My objective here is to set up a `ws` connection and API routes using oak.

Edit:
I get that Oak middlewares are only for HTTP connections, how can I use the same `app` instance to forward my `ws` requests to another middleware?

**Comment by kitsonk** [comment] 2020-06-01 09:17
Duplicate of #105.

Pending PR #137 will address.

**Closed by kitsonk** 2020-06-01 09:17 UTC
Labels: duplicate

**Comment by rishiraj824** [comment] 2020-06-01 13:46
@kitsonk Thanks for the PR, it works!!
