### ISSUE TITLE
TypeError: Type '{}' is not assignable to type 'RouteParams<R>'.

### ISSUE THREAD

**Issue by so1ve** [oakserver/oak#452] opened 2022-01-23 09:57 UTC
Error:
```
TS2322 [ERROR]: Type '{}' is not assignable to type 'RouteParams<R>'.
    params: RouteParams<R> = {},
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v10.0.0/router.ts:321:5
```
`deno.jsonc`:
```json
{
  "$schema": "https://deno.land/x/deno/cli/schemas/config-file.v1.json",
  "compilerOptions": {
    "lib": [
      "deno.ns",
      "deno.unstable",
      "dom",
      "dom.iterable",
      "dom.asynciterable"
    ],
    "strict": true
  },
  "lint": {
    "files": {
      "include": ["./"]
    },
    "rules": {
      "tags": ["recommended"],
      "include": ["ban-untagged-todo"]
    }
  },
  "fmt": {
    "files": {
      "include": ["./", "./deno.jsonc"]
    },
    "options": {
      "useTabs": false,
      "lineWidth": 80,
      "indentWidth": 2,
      "singleQuote": false,
      "proseWrap": "preserve"
    }
  }
}


```

**Comment by kitsonk** [comment] 2022-01-23 21:57
Duplicate of #438 and #439.

Please use the search function before opening new issues.

**Closed by kitsonk** 2022-01-23 21:57 UTC
Labels: duplicate

**Comment by so1ve** [comment] 2022-01-25 06:14
Sorry to bother, I checked these two issues, but they didn't help.
However, when I use v10.1.0 version of Oak and v1.18.0 version of Deno, this error keeps appearing.

**Comment by so1ve** [comment] 2022-01-25 06:17
Maybe it's my personal reason? Sorry.
