### ISSUE TITLE
When the jmeter pressure measurement stops

### ISSUE THREAD

**Issue by puzhengwu** [oakserver/oak#580] opened 2022-12-19 02:06 UTC
at Object.respondWith (deno:ext/http/01_http.js:254:21)
error: Uncaught (in promise) TypeError: cannot read headers: request closed
    return this.#request.headers;
                         ^
    at Object.get headerList (deno:ext/fetch/23_request.js:116:19)
    at Request.request.<computed> (deno:ext/fetch/23_request.js:583:62)
    at Request.get [headers] (deno:ext/fetch/23_request.js:252:48)
    at Request.get headers (deno:ext/fetch/23_request.js:467:18)
    at NativeRequest.get headers (https://deno.land/x/oak@v11.1.0/http_server_native_request.ts:68:26)
    at new Request (https://deno.land/x/oak@v11.1.0/request.ts:145:21)
    at new Context (https://deno.land/x/oak@v11.1.0/context.ts:173:20)
    at Application.#handleRequest (https://deno.land/x/oak@v11.1.0/application.ts:425:21)
    at Application.listen (https://deno.land/x/oak@v11.1.0/application.ts:610:28)
    at async file:///Volumes/mac/work/deno/webserver.ts:9:1

**Comment by rossholdway** [comment] 2022-12-20 09:22
This looks like a duplicate of https://github.com/oakserver/oak/issues/563

**Comment by kitsonk** [comment] 2023-03-03 05:14
Duplicate of #563

**Closed by kitsonk** 2023-03-03 05:14 UTC
Labels: duplicate
