### ISSUE TITLE
Oak code type errors in current deno/typescript version

### ISSUE THREAD

**Issue by cfjello** [oakserver/oak#441] opened 2021-12-22 11:15 UTC
Environment:
- windows 10
- deno --version -> v8 9.7.106.15, typescript 4.5.2
- tsc -v -> Version 4.5.2
- vscode Deno language server client v3.9.2 

The command:  deno test -A --unstable --reload
gives the following errors:

error: TS2322 [ERROR]: Type '{}' is not assignable to type 'RouteParams<R>'.
  params: RouteParams<R> = {},
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v10.0.0/router.ts:223:3

TS2322 [ERROR]: Type '{}' is not assignable to type 'RouteParams<R>'.
  let replace: RouteParams<R> = {};
      ~~~~~~~
    at https://deno.land/x/oak@v10.0.0/router.ts:227:7

TS2322 [ERROR]: Type '{}' is not assignable to type 'RouteParams<R>'.
    existingParams: RouteParams<R> = {},
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v10.0.0/router.ts:301:5

TS2322 [ERROR]: Type '{}' is not assignable to type 'RouteParams<R>'.
    params: RouteParams<R> = {},
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v10.0.0/router.ts:321:5

Found 4 errors.


The oak type errors can be avoided by downgrading: 

deno upgrade --version 1.13.0 
npm install -g typescript@4.3.5 (just to make sure that things are aligned) 

deno --version -> v8 9.3.345.11, typescript 4.3.5


However, for other reason (other Deno packages) this is not a viable solution going forward.

BR,
Claus, user: cfjello

**Comment by kitsonk** [comment] 2021-12-22 11:26
Duplicate of #438

**Closed by kitsonk** 2021-12-22 11:26 UTC
Labels: duplicate
