### ISSUE TITLE
Argument of type 'Status.BadRequest' is not assignable to parameter of type 'ErrorStatus'.

### ISSUE THREAD

**Issue by closet6** [oakserver/oak#102] opened 2020-05-21 13:08 UTC
```
error: TS2345 [ERROR]: Argument of type 'Status.BadRequest' is not assignable to parameter of type 'ErrorStatus'.
api_1  |     context.throw(Status.BadRequest, "Bad Request");
```

using example code in https://github.com/oakserver/oak/blob/master/examples/routingServer.ts

line 73

**Comment by kitsonk** [comment] 2020-05-21 23:04
Duplicate of #89 

This should be fixed in master.

**Closed** 2020-05-27 12:00 UTC
Labels: duplicate
