### ISSUE TITLE
Accessing a readable stream for `context.response`

### ISSUE THREAD

**Issue by patrickkunka** [oakserver/oak#149] opened 2020-06-05 15:43 UTC
Firstly, thanks for your effort so far in creating oak!

I'm trying trying to implement a proxy that writes data from a readable stream to the `response` of an incoming request in a granular fashion using streams.

In express I would do something like this (if I wanted to manipulate the chunks in some way):

```js
readableStream
    .on('data', chunk => {
        response.write(chunk);
    })
    .on('end', () => {
        response.status(statusCode);
        response.end();
    });
```

Or just:

```js
readableStream.pipe(writableStream);
```

Unfortunately I'm stuck right now as I can't find anyway to access an underlying [`WriteableStream`](https://developer.mozilla.org/en-US/docs/Web/API/WritableStream) interface for the response.

Is this possible?

**Comment by gjuoun** [comment] 2020-06-05 16:20
You can do it in the async way
```ts
app.use(async (ctx) => {
   const result = await ctx.request.body(true);
   const body = await Deno.readAll(result.body);
 });
```

**Comment by patrickkunka** [comment] 2020-06-05 17:35
Thanks.

Where is context response used though? How do I write (and potentially modify) chunks back to the response?

**Comment by gjuoun** [comment] 2020-06-05 17:52
```ctx.response.body = data``` is the response body you're looking for.

**Comment by patrickkunka** [comment] 2020-06-05 21:10
Thanks. Yeah I found `response.body`  but unfortunately it doesn't implement `WritableStream`. I'll take a look at `Deno.Writer` and report back.

**Comment by kitsonk** [comment] 2020-06-06 10:51
`response.body` should accept a `Deno.Reader` interface, so that responses can be asynchronously "streamed".  Possibly also accept `ReadableStream` as well.

**Comment by kitsonk** [comment] 2020-06-06 11:36
Actually I realise this is mostly a duplicate of #30.  You can pass a `Deno.Reader` already.  So you can use something like `Deno.Buffer` or the [std/io](https://github.com/denoland/deno/tree/master/std/io) interfaces.

Supporting streams though is still desirable.

**Comment by patrickkunka** [comment] 2020-06-06 13:37
Thanks a lot both. I was a bit confused by the fact that the response body could take a `Reader` but not a `Writer`, but now I see this is fundamental to the design goals of deno. Just requires a bit of shift in thinking.

So this is what I ended up with and its working nicely.

Firstly, my proxy uses `fetch` to proxy the incoming request to another server, and the goal is then that I can stream chunks from the fetch response to the server response while manipulating the throughput on the fly.

```
```

```ts
const reader = body
            .pipeThrough<Uint8Array>(myCustomTransformStreamHere))
            .getReader();

**Closed** 2020-06-06 13:52 UTC
Labels: enhancement

**Comment by patrickkunka** [comment] 2020-06-11 20:01
FYI for anyone else that needs to convert from a whatwg `ReadableStreamDefaultReader` to `Deno.Reader` while maintaining `Uint8Array` throughput, this is the util I ended up creating:

https://deno.land/x/bandwidth_throttle_stream@1.1.0/Util/readerToDenoReader.ts
