### ISSUE TITLE
app.listen doesnt work with deno compile

### ISSUE THREAD

**Issue by Teddy-Schmitz** [oakserver/oak#274] opened 2021-01-26 20:23 UTC
oak doesnt seem to start listening when using deno compile and setting the promise to a variable.  Both examples work just fine when using `deno run` 

This code doesnt work

```
const server = app.listen({ port: PORT, signal });

// Listen for SigTerm (Docker shutdown) SigInt (CTRL-C) and SIGABRT.
await Promise.any(
  [
    Deno.signal(Deno.Signal.SIGTERM),
    Deno.signal(Deno.Signal.SIGINT),
    Deno.signal(Deno.Signal.SIGABRT),
  ],
);

// Signal Oak to Shutdown
controller.abort();
// Wait for Oak to shutdown
await server;
log.info("👋 Good bye");
Deno.exit();
```

but this code works just fine

```
app.listen({ port: PORT, signal });

// Listen for SigTerm (Docker shutdown) SigInt (CTRL-C) and SIGABRT.
await Promise.any(
  [
    Deno.signal(Deno.Signal.SIGTERM),
    Deno.signal(Deno.Signal.SIGINT),
    Deno.signal(Deno.Signal.SIGABRT),
  ],
);

// Signal Oak to Shutdown
controller.abort();
log.info("👋 Good bye");
Deno.exit();
```

Any ideas on what is causing this?  I'm not sure if this is an issue with `deno compile` or oak.

The command I'm using to compile is `deno compile -A --unstable bin/server.ts`

Using Oak v6.4.2

**Comment by kitsonk** [comment] 2021-01-26 20:56
It is an issue with `deno compile` in a way. Does `deno bundle` and then running that bundle produce the same breakage? What version of Deno are you using?

**Comment by Teddy-Schmitz** [comment] 2021-01-26 22:00
yes `deno bundle` does show the same breakage

```
deno --version
deno 1.7.0 (release, x86_64-unknown-linux-gnu)
v8 8.9.255.3
typescript 4.1.3
```

**Comment by kitsonk** [comment] 2021-01-26 22:43
You could try the canary version of Deno which has an update to the bundler and see if that fixes the issue, otherwise Deno 1.7.1 will be available soon.

**Comment by Teddy-Schmitz** [comment] 2021-01-27 12:01
Tried the canary and that broke something else :laughing: the canary bundler is no longer adding in all the dependencies properly.  I'll wait for Deno 1.7.1 and hope that solves it.

**Comment by Teddy-Schmitz** [comment] 2021-01-30 22:30
Looks like the same issue is present in 1.7.1, do you know what the actual issue is?  I would be happy to open an issue for Deno to take a look at but I dont know what the problem is.

**Comment by Teddy-Schmitz** [comment] 2021-03-16 21:22
This is still happening with Deno 1.8.1 whether I bundle it or compile it.  I would be happy to report this to the Deno project but its not clear to me what the actual problem is.  If you can explain it to me I would be happy to open an issue (or it might be better for you to do so).

**Comment by transtone** [comment] 2021-04-16 13:20
this is realy big bug. 
It can't work with `Deno-1.9.0` and `oak-7.2.0` on all  platform.

**Comment by kitsonk** [comment] 2021-06-14 11:29
There were several issues resolved with bundling/compiling in Deno 1.9, 1.10 and 1.11.  Does the issues still occur with Deno 1.11?

**Comment by horihiro** [comment] 2021-11-14 09:52
This issue still occurs on `Deno@1.16.1` in the case of both `bundle` and `compile`.

I confirmed this issue by the following simple oak app.
https://github.com/oakserver/oak#application-middleware-and-context
```
import { Application, Router } from "https://deno.land/x/oak@v9.0.1/mod.ts";

const app = new Application();

app.use((ctx) => {
  ctx.response.body = "Hello World!";
});

await app.listen({ port: 8000 });
```

(compiled)
```
error: ReferenceError: Cannot access 'Response' before initialization
    at file://$deno$/bundle.js:15353:21
```

(bundled)
```
error: Uncaught ReferenceError: Cannot access 'Response' before initialization
const DomResponse = Response;
                    ^
    at file:///PATH/TO/oak_test.bundle.js:15353:21
```

**Comment by kitsonk** [comment] 2021-11-14 20:24
@horihiro that is because of #405

**Comment by lirc572** [comment] 2021-12-17 08:58
It works with deno 1.17.0!

```
deno 1.17.0 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2
```

**Comment by authcompanion** [comment] 2022-01-13 03:09
Thanks @kitsonk for everything you do for the community.

**Closed** 2022-01-13 09:52 UTC
Labels: external
